# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install ${{ matrix.toolchain }} toolchain
        run: rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update && rustup default ${{ matrix.toolchain }}

      - name: Run cargo check
        run: cargo check --all

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install ${{ matrix.toolchain }} toolchain
        run: rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update && rustup default ${{ matrix.toolchain }}

      - name: Run cargo test
        run: cargo test --all

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install ${{ matrix.toolchain }} toolchain
        run: rustup toolchain install ${{ matrix.toolchain }} --profile minimal --component rustfmt,clippy --no-self-update && rustup default ${{ matrix.toolchain }}

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all -- -D warnings
