name: Release

on:
  push:
    tags:
      - 'v*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  github-release:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - run: gh release create $VERSION --title "$VERSION" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-binary:
    name: 'Upload Binary for Linux'
    runs-on: ubuntu-latest
    needs: github-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install dependent packages
        run: sudo apt install -y musl-tools

      - run: rustup toolchain install stable --profile minimal --target x86_64-unknown-linux-musl --no-self-update && rustup default stable
      - run: cargo build --release --target=x86_64-unknown-linux-musl

      - run: cp target/x86_64-unknown-linux-musl/release/erldash erldash-${VERSION#v}.x86_64-unknown-linux-musl
      - run: gh release upload $VERSION erldash-${VERSION#v}.x86_64-unknown-linux-musl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-binary:
    name: 'Upload Binary for MacOS'
    runs-on: macos-latest
    needs: github-release
    permissions:
      contents: write
    strategy:
      matrix:
        target: ["x86_64-apple-darwin", "aarch64-apple-darwin"]
    steps:
      - uses: actions/checkout@v6

      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }} --no-self-update && rustup default stable
      - run: cargo build --release --target=${{ matrix.target }}

      - run: cp target/${{ matrix.target }}/release/erldash erldash-${VERSION#v}.${{ matrix.target }}
      - run: gh release upload $VERSION erldash-${VERSION#v}.${{ matrix.target }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: 'Publish to crates.io'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
